import localFont from "next/font/local";
import { Lora } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lora = Lora({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${lora.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
